apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-component-pac-ceea
  namespace: build-e2e-yfnh-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/psturc/test-images@sha256:927a6b0be6b17f55db9e533360b62181c971cf146142390cd563c031396ca2e8
        name: container-image
        resources: {}
status: {}
