apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-ceea
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-ceea
    app.kubernetes.io/part-of: build-suite-test-application-uspx
  name: test-component-pac-ceea
  namespace: build-e2e-yfnh-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-pac-ceea
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-pac-ceea
    spec:
      containers:
      - image: quay.io/psturc/test-images@sha256:927a6b0be6b17f55db9e533360b62181c971cf146142390cd563c031396ca2e8
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
